#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 command [arguments...]"
    exit 1
fi


cmd=("$@")
echo "#################"
echo "time command"
echo "#################"
time "${cmd[@]}"
echo "#################"
echo
echo
echo
echo "#################"
echo "calc"
echo "#################"
start_time=$(date +%s.%N)
"${cmd[@]}"
end_time=$(date +%s.%N)
execution_time=$(echo "$end_time - $start_time" | bc)
echo "#################"
echo "TIME"
echo "#################"
echo "Execution time: ${execution_time} seconds"
echo "#################"
